version: "3.8"
services:
  nuxeo:
    image: nuxeo-resource-rest-api:2021.0.0-SNAPSHOT
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      - NUXEO_DEV=true
      - NUXEO_CLID=${NUXEO_CLID}
      - NUXEO_PACKAGES=marketplace-disable-studio-snapshot-validation
    volumes:
      - ./conf.d:/etc/nuxeo/conf.d
      - data:/var/lib/nuxeo
volumes:
  data: {}
